name: Update package

on:
  push:
    tags: ['*']

permissions:
  attestations: write
  id-token: write
  packages: write
  security-events: write

jobs:
  update-package:
    name: Update package
    runs-on: ubuntu-latest
    steps:
      - id: update-package
        name: Update package
        uses: nedix/actions/update-package@main
        with:
          platforms: linux/amd64,linux/arm64/v8
          registry: ${{ secrets.REGISTRY_DOMAIN || 'ghcr.io' }}
          registry_path: ${{ secrets.REGISTRY_PATH || github.repository }}
          registry_username: ${{ secrets.REGISTRY_USERNAME || github.actor }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD || github.token }}
